services:
  - type: web
    name: barbershop-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: barbershop-db
          property: connectionString

  - type: web
    name: barbershop-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: barbershop-db
    databaseName: barbershop
    user: barbershop_user
    plan: free
